<a href="https://colab.research.google.com/github/poojithapalagani/Customer_Purchase_Prediction_ANN/blob/main/Pro1_customer_purchase_prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#step1 : importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# step2 - Load the data set
df=pd.read_csv("customer_purchase_data.csv")
df.head()

,session_id,session_duration_sec,pages_viewed,bounce,device_type,traffic_source,is_new_visitor,avg_time_per_page_sec,purchase
0,1,120,5,0,desktop,organic,1,24.00,0
1,2,340,12,0,mobile,paid,0,28.33,1
2,3,45,1,1,mobile,social,1,NaN,0
3,4,890,22,0,desktop,direct,0,40.45,1
4,5,67,2,0,tablet,email,1,33.50,0

In [ ]:
# step3:  check basic information number of rows & columns
df.shape

(100, 9)

In [ ]:
# checking data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   session_id             100 non-null    int64
 1   session_duration_sec   100 non-null    int64
 2   pages_viewed           100 non-null    int64
 3   bounce                 100 non-null    int64
 4   device_type            100 non-null    object
 5   traffic_source         100 non-null    object
 6   is_new_visitor         100 non-null    int64
 7   avg_time_per_page_sec  87 non-null     float64
 8   purchase               100 non-null    int64
dtypes: float64(1), int64(6), object(2)
memory usage: 7.2+ KB

In [ ]:
# missing values
df.isnull().sum()

session_id                0
session_duration_sec      0
pages_viewed              0
bounce                    0
device_type               0
traffic_source            0
is_new_visitor            0
avg_time_per_page_sec    13
purchase                  0
dtype: int64

In [ ]:
# step4 - Remove Unnecessary column
df.drop("session_id", axis=1, inplace=True)
df.head()

,session_duration_sec,pages_viewed,bounce,device_type,traffic_source,is_new_visitor,avg_time_per_page_sec,purchase
0,120,5,0,desktop,organic,1,24.00,0
1,340,12,0,mobile,paid,0,28.33,1
2,45,1,1,mobile,social,1,NaN,0
3,890,22,0,desktop,direct,0,40.45,1
4,67,2,0,tablet,email,1,33.50,0

In [ ]:
# step5 - Handle missing values
df['avg_time_per_page_sec'] = df['avg_time_per_page_sec'].fillna(
    df['avg_time_per_page_sec'].median()
)

In [ ]:
df.isnull().sum()

session_duration_sec     0
pages_viewed             0
bounce                   0
device_type              0
traffic_source           0
is_new_visitor           0
avg_time_per_page_sec    0
purchase                 0
dtype: int64

In [ ]:
# step6 - Encoding
df = pd.get_dummies(df, columns=['device_type', 'traffic_source'], drop_first=True)
df.head()

,session_duration_sec,pages_viewed,bounce,is_new_visitor,avg_time_per_page_sec,purchase,device_type_mobile,device_type_tablet,traffic_source_email,traffic_source_organic,traffic_source_paid,traffic_source_social
0,120,5,0,1,24.00,0,False,False,False,True,False,False
1,340,12,0,0,28.33,1,True,False,False,False,True,False
2,45,1,1,1,31.13,0,True,False,False,False,False,True
3,890,22,0,0,40.45,1,False,False,False,False,False,False
4,67,2,0,1,33.50,0,False,True,True,False,False,False

In [ ]:
# step7 - Train Test Split
X = df.drop("purchase", axis=1)
y = df["purchase"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
X_train.shape, X_test.shape

((80, 11), (20, 11))

In [ ]:
# step8 - Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train[:5]

array([[ 1.36814016,  1.35044643, -0.5       , -0.8819171 ,  0.74300881,
        -0.7540739 , -0.46056619,  2.64575131, -0.61588176, -0.57735027,
        -0.3992747 ],
       [-1.07353394, -1.03854971, -0.5       ,  1.13389342, -2.01456641,
        -0.7540739 , -0.46056619, -0.37796447, -0.61588176, -0.57735027,
         2.50454133],
       [ 0.17901316,  0.15594836, -0.5       ,  1.13389342,  0.61618636,
        -0.7540739 ,  2.17124059, -0.37796447, -0.61588176, -0.57735027,
        -0.3992747 ],
       [ 0.13541184,  0.28867037, -0.5       , -0.8819171 , -0.46993407,
         1.32612997, -0.46056619, -0.37796447, -0.61588176, -0.57735027,
        -0.3992747 ],
       [ 1.68127693,  1.74861245, -0.5       , -0.8819171 ,  0.47960834,
        -0.7540739 , -0.46056619, -0.37796447,  1.62368828, -0.57735027,
        -0.3992747 ]])

In [ ]:
# step9 - Build ANN Model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

model = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [ ]:
#step 10 - compile & Train Model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history = model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 257ms/step - accuracy: 0.5781 - loss: 0.7463 - val_accuracy: 0.5000 - val_loss: 0.7280
Epoch 2/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5938 - loss: 0.7345 - val_accuracy: 0.5000 - val_loss: 0.7195
Epoch 3/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5938 - loss: 0.7232 - val_accuracy: 0.5000 - val_loss: 0.7111
Epoch 4/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5938 - loss: 0.7119 - val_accuracy: 0.5000 - val_loss: 0.7031
Epoch 5/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5938 - loss: 0.7023 - val_accuracy: 0.5000 - val_loss: 0.6951
Epoch 6/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5938 - loss: 0.6914 - val_accuracy: 0.5000 - val_loss: 0.6874
Epoch 7/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5938 - loss: 0.6820 - val_accuracy: 0.5625 - val_loss: 0.6800
Epoch 8/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5938 - loss: 0.6725 - val_accuracy: 0.5625 - val_loss: 0.6729
Epoch 9/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5938 - loss: 0.6630 - val_accuracy: 0.5625 - val_loss: 0.6665
Epoch 10/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6094 - loss: 0.6547 - val_accuracy: 0.5625 - val_loss: 0.6603
Epoch 11/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.6094 - loss: 0.6460 - val_accuracy: 0.5625 - val_loss: 0.6542
Epoch 12/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.6094 - loss: 0.6381 - val_accuracy: 0.5625 - val_loss: 0.6484
Epoch 13/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6094 - loss: 0.6300 - val_accuracy: 0.5625 - val_loss: 0.6429
Epoch 14/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6094 - loss: 0.6229 - val_accuracy: 0.5625 - val_loss: 0.6375
Epoch 15/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6094 - loss: 0.6162 - val_accuracy: 0.5625 - val_loss: 0.6330
Epoch 16/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.6096 - val_accuracy: 0.5625 - val_loss: 0.6289
Epoch 17/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.6031 - val_accuracy: 0.5625 - val_loss: 0.6250
Epoch 18/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6094 - loss: 0.5970 - val_accuracy: 0.5625 - val_loss: 0.6213
Epoch 19/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.5906 - val_accuracy: 0.5625 - val_loss: 0.6178
Epoch 20/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6094 - loss: 0.5849 - val_accuracy: 0.5625 - val_loss: 0.6143
Epoch 21/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.6094 - loss: 0.5788 - val_accuracy: 0.5625 - val_loss: 0.6109
Epoch 22/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6094 - loss: 0.5728 - val_accuracy: 0.5625 - val_loss: 0.6076
Epoch 23/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.5670 - val_accuracy: 0.5625 - val_loss: 0.6043
Epoch 24/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.6094 - loss: 0.5613 - val_accuracy: 0.5625 - val_loss: 0.6012
Epoch 25/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6094 - loss: 0.5561 - val_accuracy: 0.5625 - val_loss: 0.5981
Epoch 26/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6094 - loss: 0.5507 - val_accuracy: 0.5625 - val_loss: 0.5951
Epoch 27/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6094 - loss: 0.5456 - val_accuracy: 0.5625 - val_loss: 0.5922
Epoch 28/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6094 - loss: 0.5406 - val_accuracy: 0.5625 - val_loss: 0.5893
Epoch 29/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6094 - loss: 0.5356 - val_accuracy: 0.5625 - val_loss: 0.5865
Epoch 30/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6094 - loss: 0.5308 - val_accuracy: 0.5625 - val_loss: 0.5838

In [ ]:
# step 11.1 - Predictions
y_pred = (model.predict(X_test) > 0.5).astype(int)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step

In [ ]:
# step 11.2 - Calculate Metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

Accuracy: 0.6
Precision: 0.0
Recall: 0.0
F1 Score: 0.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
# Step 11.3 - confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[12  0]
 [ 8  0]]

In [ ]:
# step 12 - compare with SGD Optimizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

model_sgd = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [ ]:
model_sgd.compile(
    optimizer='sgd',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history_sgd = model_sgd.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 236ms/step - accuracy: 0.5938 - loss: 0.6369 - val_accuracy: 0.5625 - val_loss: 0.7414
Epoch 2/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6094 - loss: 0.6329 - val_accuracy: 0.5625 - val_loss: 0.7384
Epoch 3/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.6094 - loss: 0.6290 - val_accuracy: 0.5625 - val_loss: 0.7354
Epoch 4/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6094 - loss: 0.6251 - val_accuracy: 0.5625 - val_loss: 0.7326
Epoch 5/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6094 - loss: 0.6218 - val_accuracy: 0.5625 - val_loss: 0.7298
Epoch 6/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6094 - loss: 0.6177 - val_accuracy: 0.5625 - val_loss: 0.7271
Epoch 7/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.6143 - val_accuracy: 0.5625 - val_loss: 0.7246
Epoch 8/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.6094 - loss: 0.6107 - val_accuracy: 0.5625 - val_loss: 0.7221
Epoch 9/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.6094 - loss: 0.6072 - val_accuracy: 0.5625 - val_loss: 0.7197
Epoch 10/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6094 - loss: 0.6042 - val_accuracy: 0.5625 - val_loss: 0.7173
Epoch 11/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.6008 - val_accuracy: 0.5625 - val_loss: 0.7150
Epoch 12/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6094 - loss: 0.5975 - val_accuracy: 0.5625 - val_loss: 0.7126
Epoch 13/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6094 - loss: 0.5943 - val_accuracy: 0.5625 - val_loss: 0.7104
Epoch 14/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6094 - loss: 0.5912 - val_accuracy: 0.5625 - val_loss: 0.7080
Epoch 15/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.6094 - loss: 0.5881 - val_accuracy: 0.5625 - val_loss: 0.7056
Epoch 16/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.5851 - val_accuracy: 0.5625 - val_loss: 0.7033
Epoch 17/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.5822 - val_accuracy: 0.5625 - val_loss: 0.7010
Epoch 18/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.5793 - val_accuracy: 0.5625 - val_loss: 0.6988
Epoch 19/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.5765 - val_accuracy: 0.5625 - val_loss: 0.6966
Epoch 20/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6094 - loss: 0.5737 - val_accuracy: 0.5625 - val_loss: 0.6945
Epoch 21/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6094 - loss: 0.5710 - val_accuracy: 0.5625 - val_loss: 0.6924
Epoch 22/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.5684 - val_accuracy: 0.5625 - val_loss: 0.6904
Epoch 23/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.5658 - val_accuracy: 0.5625 - val_loss: 0.6883
Epoch 24/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6094 - loss: 0.5630 - val_accuracy: 0.5625 - val_loss: 0.6864
Epoch 25/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6094 - loss: 0.5606 - val_accuracy: 0.5625 - val_loss: 0.6844
Epoch 26/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6094 - loss: 0.5581 - val_accuracy: 0.5625 - val_loss: 0.6825
Epoch 27/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.5557 - val_accuracy: 0.5625 - val_loss: 0.6806
Epoch 28/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6094 - loss: 0.5535 - val_accuracy: 0.5625 - val_loss: 0.6788
Epoch 29/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6094 - loss: 0.5511 - val_accuracy: 0.5625 - val_loss: 0.6769
Epoch 30/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6250 - loss: 0.5489 - val_accuracy: 0.5625 - val_loss: 0.6753

In [ ]:
y_pred_sgd = (model_sgd.predict(X_test) > 0.5).astype(int)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

print("Accuracy:", accuracy_score(y_test, y_pred_sgd))
print("Precision:", precision_score(y_test, y_pred_sgd))
print("Recall:", recall_score(y_test, y_pred_sgd))

Accuracy: 0.6
Precision: 0.0
Recall: 0.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))